#!/bin/bash
#SBATCH --job-name=cellranger_multi_counts
#SBATCH --output=cellranger_multi_counts.out   
#SBATCH --error=cellranger_multi_counts.err    
#SBATCH --time=165:00:00
#SBATCH --cpus-per-task=16
#SBATCH --mem=500G
#SBATCH --partition=defq
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=m.afechkar@amsterdamumc.nl

module load cellranger

# Defining base paths
BASE_DIR="/net/beegfs/scratch/mafechkar/MDS_Data"
CONFIG_FILE="$BASE_DIR/metadata/multi_config.csv"
OUTPUT_DIR="$BASE_DIR/MDS_Output"

mkdir -p "$OUTPUT_DIR"

cd "$OUTPUT_DIR" || { echo "ERROR: Cannot change directory to $OUTPUT_DIR"; exit 1; }

# Print  start message
echo "Starting Cell Ranger Multi at $(date)..."

# Running Cell Ranger Multi using the configuration file
cellranger multi --id=MDS_Output --csv="$CONFIG_FILE" --localcores=16 --localmem=500 2>&1 | tee cellranger_multi.log

# Print a finish message
echo "Cell Ranger Multi finished at $(date). Output is in: $OUTPUT_DIR"

       cat cellranger_multi_counts.out
Starting Cell Ranger Multi at Fri Feb 28 12:24:27 CET 2025...


Thank you for using cellranger. To help us improve our product,
anonymized telemetry data has been collected and sent to 10X Genomics.
This data helps us understand usage patterns, diagnose issues,
and prioritize improvements.

You can inspect the telemetry metrics sent by looking in
/trinity/home/mafechkar/.cache/tenx/telemetry/cellranger/cellranger-9.0.0

For more details on what data is collected and how it's used, please visit
https://10xgen.com/pipeline-telemetry

You can disable telemetry at any time by running the following command:
        cellranger telemetry disable
Martian Runtime - v4.0.13
2025-02-28 12:24:27 [jobmngr] WARNING: User-supplied amount 300 GB is higher than the detected cgroup memory limit of 40.0 GB
Serving UI at http://node010.cluster:45149?auth=VT73bLDSZJWieK49KKgZ4ycehgpWZLOMSSEHQ85E-N0

Running preflight checks (please wait)...

[error] Pipestance failed. Error log at:
MDS_Output/SC_MULTI_CS/MULTI_PREFLIGHT/fork0/chnk0-u5de6c19ceb/_errors

Log message:
failed to parse CSV at line: 1, col: 1

Waiting 6 seconds for UI to do final refresh.
Pipestance failed. Use --noexit option to keep UI running after failure.

2025-02-28 12:24:34 Shutting down.
Saving pipestance info to "MDS_Output/MDS_Output.mri.tgz"
For assistance, upload this file to 10x Genomics by running:

cellranger upload <your_email> "MDS_Output/MDS_Output.mri.tgz"

Cell Ranger Multi finished at Fri Feb 28 12:24:42 CET 2025. Output is in: /net/beegfs/scratch/mafechkar/MDS_Data/MDS_Output
